version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    REPOSITORY_URI: 881601364561.dkr.ecr.ap-south-1.amazonaws.com/librarymanagement-registry

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Install phase started

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws sts get-caller-identity
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | cut -d":" -f2)
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json
      - printf '[{"name":"librarymanagement-registry","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/library-management-system.jar